# Generated by Django 5.1 on 2025-04-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected'), ('In Process...', 'In Process...')], default='Pending', max_length=20),
        ),
    ]
