# Generated by Django 5.1 on 2025-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamb',
            name='players',
            field=models.ManyToManyField(to='app.player_details'),
        ),
    ]
