# Generated by Django 5.1 on 2025-04-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_players_added_to_team_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_added_to_team_a',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teama'),
        ),
        migrations.CreateModel(
            name='Players_added_to_team_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player_details')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_players', to='app.teamb')),
            ],
            options={
                'verbose_name': 'Player Added to Team B',
                'verbose_name_plural': 'Players Added to Team B',
                'unique_together': {('team', 'player')},
            },
        ),
    ]
