# Generated by Django 5.1 on 2025-04-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_players_added_to_team_b_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players_added_to_team_b',
        ),
    ]
