# Generated by Django 5.1 on 2025-04-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_players_added_to_team_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players_added_to_team_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player_details')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teamb')),
            ],
        ),
    ]
