# Generated by Django 5.1 on 2025-04-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_players_added_to_team_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players_added_to_team_b',
        ),
    ]
