# Generated by Django 5.1 on 2025-04-24 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_players_added_to_team_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players_added_to_team_b',
            options={'ordering': ['-date_added'], 'verbose_name': 'Team B Player Assignment', 'verbose_name_plural': 'Team B Player Assignments'},
        ),
        migrations.AddField(
            model_name='players_added_to_team_b',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='players_added_to_team_b',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='players_added_to_team_b',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='players_added_to_team_b',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_assignments', to='app.player_details', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='players_added_to_team_b',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_additions', to='app.teamb', verbose_name='Team B'),
        ),
        migrations.AddIndex(
            model_name='players_added_to_team_b',
            index=models.Index(fields=['team', 'player'], name='app_players_team_id_d4f8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='players_added_to_team_b',
            index=models.Index(fields=['date_added'], name='app_players_date_ad_e9b7fa_idx'),
        ),
    ]
