# Generated by Django 5.1 on 2025-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_players_added_to_team_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_details',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player_details',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport_club',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport_club',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
