# Generated by Django 5.1 on 2025-05-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_player_details_latitude_player_details_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_details',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='player_details',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sport_club',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sport_club',
            name='longitude',
        ),
    ]
