# Generated by Django 5.1 on 2025-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_player_details_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_details',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
