# Generated by Django 5.1 on 2025-05-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_player_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_club',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
