# Generated by Django 5.1 on 2025-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sport_club_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_players',
            field=models.JSONField(default=list),
        ),
    ]
