# Generated by Django 5.1 on 2025-06-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_booking_no_of_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_players',
            new_name='selected_players',
        ),
    ]
